# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

questions = Question.create([
    {q_text: "You’re really busy at work and a colleague is telling you their life story and personal woes. You:"},
    {q_text: "You’ve been sitting in the doctor’s waiting room for more than 25 minutes. You:"},
    {q_text: "You’re having an animated discussion with a colleague regarding a project that you’re in charge of. You:"},
    {q_text: "You are taking part in a guided tour of a museum. You:"},
    {q_text: "During dinner parties at your home, you have a hard time with people who:"},
    {q_text: "You crack a joke at work, but nobody seems to have noticed. You:"},
    {q_text: "This morning, your agenda seems to be free. You:"},
    {q_text: "During dinner, the discussion moves to a subject about which you know nothing at all. You:"},
    {q_text: "You’re out with a group of friends and there’s a person who’s quite shy and doesn’t talk much. You:"},
    {q_text: "At work, somebody asks for your help for the hundredth time. You:"},
    {q_text: "You’ve been see a movie with your family and the reviews are mixed. You:"},
    {q_text: "A friend arrives late for your meeting. You:"},
    {q_text: "You can’t find your car keys. You:"},
    {q_text: "It’s time for your annual appraisal with your boss. You:"},
])

answers = Answer.create([
    {a_text: "Go with great hesitation as these sessions are torture for you", a_point:3, question_id:14},
    {a_text: "Look forward to hearing what your boss thinks about you and expects from you", a_point:2, question_id:14},
    {a_text: "Rehearse ad nauseam the arguments and ideas that you’ve prepared for the meeting", a_point:1, question_id: 14},
    {a_text: "Go along unprepared as you are confident and like improvising", a_point:0, question_id: 14},
    {a_text: "Don’t want anyone to find out, so you take the bus instead", a_point:3, question_id: 13},
    {a_text: "Panic and search madly without asking anyone for help", a_point:2, question_id: 13},
    {a_text: "Grumble without telling your family why you’re in a bad mood", a_point:1, question_id: 13},
    {a_text: "Accuse those around you for misplacing them", a_point:0, question_id: 13},
    {a_text: "Say, ‘It’s not a problem,’ even if that’s not what you really think", a_point:3, question_id: 12},
    {a_text: "Give them a filthy look and sulk for the rest of the evening", a_point:2, question_id: 12},
    {a_text: "Tell them, ‘You’re too much! Have you seen the time?’", a_point:1, question_id: 12},
    {a_text: "Make a scene in front of everyone", a_point:0, question_id: 12},
    {a_text: "Don’t share your point of view with anyone", a_point:3, question_id: 11},
    {a_text: "Didn’t like the film, but keep your views to yourself when asked", a_point:2, question_id: 11},
    {a_text: "State your point of view with enthusiasm", a_point:1, question_id: 11},
    {a_text: "Try to bring the others round to your point of view", a_point:0, question_id: 11},
    {a_text: "Give them a hand, as usual", a_point:3, question_id: 10},
    {a_text: "Accept — you’re known for being helpful", a_point:2, question_id: 10},
    {a_text: "Ask them, please, to find somebody else for a change", a_point:1, question_id: 10},
    {a_text: "Loudly make it known that you’re annoyed", a_point:0, question_id: 10},
    {a_text: "Notice that they’re alone, but don’t go over to talk with them", a_point:3, question_id: 9},
    {a_text: "Go and have a chat with them", a_point:2, question_id: 9},
    {a_text: "Shoot some friendly smiles in their direction", a_point:1, question_id: 9},
    {a_text: "Hardly notice them at all", a_point:0, question_id: 9},
    {a_text: "Don’t dare show that you don’t know anything about the subject", a_point:3, question_id: 8},
    {a_text: "Barely follow the discussion", a_point:2, question_id: 8},
    {a_text: "Ask lots of questions to learn more about it", a_point:1, question_id: 8},
    {a_text: "Change the subject of discussion", a_point:0, question_id: 8},
    {a_text: "Know that somebody will find a reason to come and bother you", a_point:3, question_id: 7},
    {a_text: "Heave a sigh of relief and look forward to a day without stress", a_point:2, question_id: 7},
    {a_text: "Question your colleagues about a project that’s been worrying you", a_point:1, question_id: 7},
    {a_text: "Pick up the phone and start filling up your agenda with meetings", a_point:0, question_id: 7},
    {a_text: "Think it’s for the best — it was a lame joke anyway", a_point:3, question_id: 6},
    {a_text: "Wait to share it with your friends after work", a_point:2, question_id: 6},
    {a_text: "Try again a bit later with one of your colleagues", a_point:1, question_id: 6},
    {a_text: "Keep telling it until they pay attention", a_point:0, question_id: 6},
    {a_text: "Ask you to tell a story in front of everyone else", a_point:3, question_id: 5},
    {a_text: "Talk privately between themselves", a_point:2, question_id: 5},
    {a_text: "Hang around you all evening", a_point:1, question_id: 5},
    {a_text: "Always drag the conversation back to themselves", a_point:0, question_id: 5},
    {a_text: "Are a bit too far towards the back so don’t really hear what the guide is saying", a_point:3, question_id: 4},
    {a_text: "Follow the group without question", a_point:2, question_id: 4},
    {a_text: "Make sure that everyone is able to hear properly", a_point:1, question_id: 4},
    {a_text: "Are right up the front, adding your own comments in a loud voice", a_point:0, question_id: 4},
    {a_text: "Don’t dare contradict them", a_point:3, question_id: 3},
    {a_text: "Think that they are obviously right", a_point:2, question_id: 3},
    {a_text: "Defend your own point of view, tooth and nail", a_point:1, question_id: 3},
    {a_text: "Continuously interrupt your colleague", a_point:0, question_id: 3},
    {a_text: "Look at your watch every two minutes", a_point:3, question_id: 2},
    {a_text: "Bubble with inner anger, but keep quiet", a_point:2, question_id: 2},
    {a_text: "Explain to other equally impatient people in the room that the doctor is always running late", a_point:1, question_id: 2},
    {a_text: "Complain in a loud voice, while tapping your foot impatiently", a_point:0, question_id: 2},
    {a_text: "Don’t dare to interrupt them", a_point:3, question_id: 1},
    {a_text: "Think it’s more important to give them some of your time; work can wait", a_point:2, question_id: 1},
    {a_text: "Listen, but with only with half an ear", a_point:1, question_id: 1},
    {a_text: "Interrupt and explain that you are really busy at the moment", a_point:0, question_id: 1}
])
